// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAJ3MXGTdzqT45Bc189-cce7aPcxqscAU',
    appId: '1:579111689428:web:74d601649b3ccc7749af41',
    messagingSenderId: '579111689428',
    projectId: 'al-marhum',
    authDomain: 'al-marhum.firebaseapp.com',
    storageBucket: 'al-marhum.firebasestorage.app',
    measurementId: 'G-PBBDT3B8JK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqCucxGpq6Ue6n5Ht8Bbx3wr4gXg7pvuM',
    appId: '1:579111689428:android:24f60920e7e270cc49af41',
    messagingSenderId: '579111689428',
    projectId: 'al-marhum',
    storageBucket: 'al-marhum.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7-TYZfcSWISYAxhs_cdY_IDJVOao1iMg',
    appId: '1:579111689428:ios:1353ededbb2f0eb849af41',
    messagingSenderId: '579111689428',
    projectId: 'al-marhum',
    storageBucket: 'al-marhum.firebasestorage.app',
    iosBundleId: 'com.uthm.psm',
  );

}